title   lindu linux (x86_64)
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=arch archiso_iso_sfx=.iso archiso_loop_sfx=.iso archiso_pxe_sfx=.iso copytoram=n archisolabel=LINDU_LABEL