#
# /etc/pacman.conf — конфигурация пакетного менеджера lindu linux
# (используется и для сборки образа)
#

[options]
#ParallelDownloads = 5
HoldPkg      = pacman glibc
Architecture = auto
SigLevel     = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Для драйверов NVIDIA и 32-битных библиотек раскомментируйте:
[multilib]
Include = /etc/pacman.d/mirrorlist